import Head from "next/head";
import Image from 'next/image';
import Link from 'next/link';
import styles from "@/styles/Home.module.css";
import data from '../data/data.json'
import {GetServerSideProps} from 'next'
import {IEventsCat} from "../types/types"


interface HomeProps {
  data: IEventsCat[] 
}


export default function Home({data}: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          {/* <img src="" alt="" /> */}
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about">About Us</Link>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map(ev => <a key={ev.id} href={`/events/${ev.id}`}>
          <Image src={ev.image} alt={ev.title} width={200} height={200}/>
          <h2>{ev.title}</h2>
          <p>{ev.description}</p>
        </a>)}
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}


export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      data: data.events_categories,
    },
  };
};